### ISSUE TITLE
OpenAPT fails to load schema due to deprecated call to yaml.load without Loader argument

### ISSUE THREAD

**Issue by spirent-leetaylor** [ALLOcloud/OpenAPT#6]
When working on Debian 12/bookworm with python3.11 I see the following error:

**Traceback (most recent call last):
  File "/home/ltaylor/.local/bin/openapt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ltaylor/.local/lib/python3.11/site-packages/allocloud/openapt/__main__.py", line 64, in main
    run(\*\*args)
  File "/home/ltaylor/.local/lib/python3.11/site-packages/allocloud/openapt/__init__.py", line 37, in run
    _schema = yaml.load(f)
              ^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'**

Please see https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
